### ISSUE TITLE
AttributeError: 'Data' object has no attribute 'get'

### ISSUE THREAD

**Issue by cyrusjk** [vooon/hass-radiacode#38]
## Configuration

```yaml
none
```

## Describe the bug

Will connect then log the attached error. Then, after a few seconds, disconnect.

## Debug log

```text
2022-01-29 14:43:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _async_write_ha_state
    self.device_state_attributes is not None
  File "/config/custom_components/radiacode_bt/entity.py", line 42, in device_state_attributes
    "id": str(self.coordinator.data.get("id")),
AttributeError: 'Data' object has no attribute 'get'
```

**Comment by vooon** [comment]
Hello,

I'm also having similar troubles, plugin currently incomplete.

Some of the troubles that i cannot use it at the same time with passive ble plugin.
I initially blamed my QEMU OVA setup with USB pass-trough for BT dongle, because library's examples works fine.
But not inside homeassistant environment :(. I actually thought to write esphome config instead, but unfortunately i already had have long backlog.

**Comment by cyrusjk** [comment]
That is definitely disappointing to hear. Python is not my specialty, but can you help me understand where this problem is? Is it in mapping the data being returned from the unit?

**Comment by vooon** [comment]
Somewhere in that function: https://github.com/vooon/hass-radiacode/blob/main/custom_components/radiacode_bt/__init__.py#L114

**Comment by vooon** [comment]
You can run examples from library https://github.com/cdump/radiacode
they works as expected. It might be easier to me write simple MQTT publisher based on "narod_mon.py".

**Comment by cyrusjk** [comment]
Publishing to something like MQTT might make debugging simpler as well as create a potential to run the integration outside of HA. Plus, once it is in an MQTT topic it can be ingested by anyone, not just HA.
